### ISSUE TITLE
🐛 [BUG] QR code not read by Galaxy S22 or my Galaxy Fold5

### ISSUE THREAD

**Issue by nickglott** [MarksMakerSpace/filament-profiles#12]
I am unable to scan a sigle bar code on my Galaxy S22 or my Galaxy Fold5. They can on my computer but I am thinking they are too small and not enough detail to make it out? Anyone else able to scan them? Maybe just Samsung? have tried the camera app and multiple differet QR scaning apps. 

I know size is really limited but maybe just a little bit bigger or a different QR code style. I like the little spool in the middle haha but maybe dots might work better as they would be a little more seperated and less blending together?

I am using the Phomemo M110 and they look to be detailed but maybe just blending in a bit too much? Maybe I am the only one, not really any settings on the printer can change except darkness have tried 6 and 10.

**Comment by markcarroll** [comment]
Hey @nickglott , can you try this:
![filament-bambu-lab-abs-Basic-White (3)](https://github.com/user-attachments/assets/0dffc448-8cee-4aa7-b58d-35f83ae3cf43)

**Comment by markcarroll** [comment]
@nickglott I deployed a simplified QR code to production yesterday. Let me know how the new one works for you.

**Comment by nickglott** [comment]
@markcarroll Sorry been very busy! QR scanning app did read the new QR codes, samsung camera app did not however not the 1st time I have had trouble scanning w/ the camera app. So I think it is good now. Appreciate the effort!
