### ISSUE TITLE
💡 [FEAT] Missing material type for eSun

### ISSUE THREAD

**Issue by 11Chris11** [MarksMakerSpace/filament-profiles#15]
**Is your feature request related to a problem? Please describe.**

**Describe the solution you'd like**

**Describe alternatives you've considered**

**Additional context**

**Comment by 11Chris11** [comment]
Hi there, great site with good overview. Can you add "Lite" as a seperate material please? eSun PLA-Lite is a bit different to the eSun PLA Basic, so it would be nice to have this material in that list. Thanks a lot in advance.

**Comment by 11Chris11** [comment]
> Hi there, great site with good overview. Can you add "Lite" as a seperate material please? eSun PLA-Lite is a bit different to the eSun PLA Basic, so it would be nice to have this material in that list. Thanks a lot in advance.

Just found the possibility to add the material on my own, ty

**Comment by markcarroll** [comment]
Added. LMK if you need anything else.
