### ISSUE TITLE
🐛 [BUG] Some filaments without logos do not display text in labellife

### ISSUE THREAD

**Issue by Arachnid** [MarksMakerSpace/filament-profiles#16]
Filing a bug request as per this thread: https://www.reddit.com/r/3dfilamentprofiles/comments/1gnffo8/manufacturer_logos_not_showing_up_in_labellife/

I've attached filament profiles before and after making the text reappear.
[filament-fiberlogy-pctg-Translucent-Transparent.zip](https://github.com/user-attachments/files/17707811/filament-fiberlogy-pctg-Translucent-Transparent.zip)

**Comment by markcarroll** [comment]
@Arachnid It is definitely the fonts. It looks like my Mac's Apple font got written in but you are on Windows.  I think I have picked a universal font now.  Can you give this one a try please. 
[filament-fiberlogy-pctg-Translucent-Transparent new.aml.zip](https://github.com/user-attachments/files/17782324/filament-fiberlogy-pctg-Translucent-Transparent.new.aml.zip)

**Comment by markcarroll** [comment]
This should be fixed now. I am specifying a cross-platform font for all the text boxes. Re-open if you are still having an issue.

**Comment by wkearney99** [comment]
I'm trying to print some Inland PETG Basic and the brand text box is not showing text.  

![image](https://github.com/user-attachments/assets/34999f48-0424-4523-ae10-ce6021201718)

If I change the font to Tahoma it immediately shows up.  If I select Arial again, it also remains visible.  

I THINK I FOUND THE PROBLEM.  I downloaded this filament as a native AML file and looked at the XML.  
https://3dfilamentprofiles.com/filaments/2047/details

Arial is misspelled as Ariel in a fontInfos-fontName element at line 75
