### ISSUE TITLE
💡 [FEAT] In the search, in the 3 dot menu on the right side, add a "Add to My Filaments" quick action. 

### ISSUE THREAD

**Issue by mharris1984** [MarksMakerSpace/filament-profiles#22]
Like in the title, add a quick action for "Add to my Filaments" in the 3dot menu in the search results.  

Or a checkbox column for selecting multiple results and do bulk add to my filaments.  And if it already exists in the filaments, then add a spool to the spools on hand. 

This way, when I get a bulk order of 15 new filimants to add new colors to my collection or refil low running existing filaments on hand, its a simple one click easy action.  Not having to search, select, click add, back to search, select, click add, etc....

**Comment by markcarroll** [comment]
I had the 3dot menu option on the list but not the multi-select yet.  Added.

**Comment by mharris1984** [comment]
Awesome!  Thank you!  Building my profile out with my 60 or so spools is a pain adding one by one.  But loving the information all in one spot!

**Comment by markcarroll** [comment]
closing this as the menu option is now there. feel free to open a new one if you need more or you find a problem.

**Comment by markcarroll** [comment]
adding one more comment - @mharris1984 go take a look now. This should be a lot easier, no page navigation required.
