### ISSUE TITLE
🐛 [BUG] A bunch of "links" in the Bambu Filaments are going to a 404 page. 

### ISSUE THREAD

**Issue by mharris1984** [MarksMakerSpace/filament-profiles#23]
**Describe the bug**
Bambu Filaments - The link to the Bambu Store site is bringing up 404 not found pages.  It appears Bambu recently moved a bunch of filaments to new pages on their store, so the old links are broken. 

Example:
ABS Orange Bambu Filament link on site goes to - https://us.store.bambulab.com/de/products/abs-filament-de?variant=46748172222812

The correct address is now - https://us.store.bambulab.com/collections/asa-abs/products/abs-filament?variant=42512931750024+

So where you have /de/ that should be replaced with /collections/asa-abs/

It might be because the link on the site is trying to initially go to the EU store, but the redirects to US store since my account is signed in.  And the US site address is different from the EU site. However, when I change my region to EU, it keeps the same /collections/<filamenttype>/ new URL.  So maybe Bambu updated their store URL locations.

**Comment by markcarroll** [comment]
Hey @mharris1984 , thanks for the heads up on this one.  I wrote some code today to parse the filaments on the BL web site and update the data in our database, so now there should be more up to date links for most of the filaments.  There were some that didn't match so not all of them are updated yet, but I will continue to refine my matching algorithm to try and improve it.  

Closing this for now though. Feel free to open another ticket if you find anything else.
