### ISSUE TITLE
:bulb: [FEAT] Add Paging

### ISSUE THREAD

**Issue by BlackRose01** [MarksMakerSpace/filament-profiles#28]
Hey,

in order to reduce the load of the API and the clients a Paging functionality should be implemented. This is also a good way to reduce the maximum number of results per request.

KR,
BlackRose01

**Comment by markcarroll** [comment]
Yes, agreed. I have started this already.  The UI was fine when I had 43 filaments. Now that we are over 1,300 is not handling it well.

**Comment by markcarroll** [comment]
Done. Deploying now.
