### ISSUE TITLE
🐛 [BUG] QR Code of Filament is not usable

### ISSUE THREAD

**Issue by BlackRose01** [MarksMakerSpace/filament-profiles#29]
**Describe the bug**
A QR Code Scanner cannot recognize the QR Code on any Filament page.

**To Reproduce**
1. Go to 'Filament List'
2. Click on any Filament
3. Scan QR Code

**Expected behavior**
The page of the filament from the manufacturer.

**Smartphone (please complete the following information):**
 - Device: Samsung S24 Ultra
 - OS: Android 14

**Additional context**
In my opinion it could be a problem with the image on the QR Code.

**Comment by markcarroll** [comment]
Thank you for reporting this. This is now fixed.  If there is a manufacturer link (and not an Amazon link) it will be shown on this QR.
