### ISSUE TITLE
💡 [FEAT] Add Bambu PETG HF

### ISSUE THREAD

**Issue by mhunt407** [MarksMakerSpace/filament-profiles#3]
**Is your feature request related to a problem? Please describe.**
I'd like to add some of the new Bambu PETG HF, but we're missing the HF option under material type.

**Describe the solution you'd like**
Please can you add HF?

Thanks!

**Comment by markcarroll** [comment]
@mhunt407 Added. I also added the defaults for BL PETG HF to the table so that if you only enter the material, color and RGB, the rest should get pulled from the defaults. see [this comment](https://github.com/MarksMakerSpace/filament-profiles/issues/4#issuecomment-2248718977)
