### ISSUE TITLE
💡 [FEAT] Please allow the adding of Exotic materials

### ISSUE THREAD

**Issue by Zaroz** [MarksMakerSpace/filament-profiles#31]
**Is your feature request related to a problem? Please describe.**
I recently tried to add [this filament](https://www.amazon.com/gp/product/B0CZKVZLLB/ref=ppx_yo_dt_b_search_asin_title?ie=UTF8&th=1), but there was no option for SMP/4D Filament.

**Describe the solution you'd like**
I understand that SMP is an exotic, niche material, so it is not like it needs it's own full category 
Please add an "Exotic" option for "Material" that allows for a manual custom text entry in the "Material Type" Category .
Here's an image to illustrate:
![Screenshot 2024-12-05 at 17-30-29 3D Filament Profiles](https://github.com/user-attachments/assets/fcd9ba7b-51e7-4c30-81a3-dd0ec1bd3e31)

**Describe alternatives you've considered**
I currently am classifying it as a type of TPU, which is **very** inaccurate.

**Additional context**

This would not just help in my specific case, but also in the case of anyone else with an exotic filament that doesn't fit into the existing categories.

**Comment by markcarroll** [comment]
Sorry this took so long. I have added SMP as a material. Since the price was attainable for hobbyists I figured I might as well add it as a first class citizen.  I will take your suggestion of adding a text field though.
