### ISSUE TITLE
💡 [FEAT] Add "Flexible" or "95A" as a Material Type to allow a filament of "Amolen TPU Flexible"

### ISSUE THREAD

**Issue by Vahalas** [MarksMakerSpace/filament-profiles#32]
**Is your feature request related to a problem? Please describe.**
Not a problem, just wanted to Add Amolen TPU which Amolen describes with a sub-type of "Flexible"

**Describe the solution you'd like**
I'd like to be able to select "Flexible" as the Type when editing my filament profile for the Amolen TPU

**Describe alternatives you've considered**
I can use --Other-- but it doesn't look as nice when printing labels

**Additional context**
N/A

**Comment by markcarroll** [comment]
Done. Sorry that took so long.  I added 95A, 85A and 68D.
