### ISSUE TITLE
💡 [FEAT]  Please add JPEG for newly-added filament

### ISSUE THREAD

**Issue by luckygreen** [MarksMakerSpace/filament-profiles#46]
**Is your feature request related to a problem? Please describe.**
A user can't manually upload an image to be associated with a newly-added filament. (For understandable reasons). Which means the admin has to do it by hand. ;-)

**Describe the solution you'd like**
Display the attached JPEG for the following filament that I just added, which is no longer being manufactured:
https://3dfilamentprofiles.com/my/filaments/details/1940

**Describe alternatives you've considered**

**Additional context**
![PLA-Tough_Silver_large](https://github.com/user-attachments/assets/ab5e9cdf-d1bf-4796-babb-0540425c42b6)

**Comment by markcarroll** [comment]
done

**Comment by luckygreen** [comment]
👍️
Now the page looks "complete".
