### ISSUE TITLE
🐛 [BUG] Filter by Type | Material -> PLA+/Pro searches for "pla-plus" instead of "PLA+/Pro"

### ISSUE THREAD

**Issue by ch33tah0** [MarksMakerSpace/filament-profiles#51]
**Describe the bug**
Filter by Type Material PLA+/Pro gives no results.
I guess at some point there was a rename?

**To Reproduce**
https://3dfilamentprofiles.com/filaments/by-type
Select Material "PLA+/Pro" -> GO -> no result (searched for "pla-plus")

**Comment by markcarroll** [comment]
Good catch. Thank you for reporting.
