### ISSUE TITLE
[Suggestion] Manufacturer addition request

### ISSUE THREAD

**Issue by k-piekarczyk** [MarksMakerSpace/filament-profiles#55]
If possible, please add Spectrum Filaments to the list of manufacturers.

Link to their webpage: https://spectrumfilaments.com/en/

**Comment by markcarroll** [comment]
@k-piekarczyk  `Spectrum` is already there. Should we change the name to `Spectrum Filaments`?

**Comment by k-piekarczyk** [comment]
Ah, no need to do that, I just didn't notice it's there 😅 Thank you for a quick response, I'll close the issue now.

**Comment by k-piekarczyk** [comment]
@markcarroll though while I have you here, it would be awesome if you added the `Pastello` material type (or the ability to add own material types, but it's a bigger ask), here's an example: https://shop.spectrumfilaments.com/product-eng-1514-Filament-Pastello-PLA-1-75mm-FLAMINGO-RED-1kg.html

**Comment by markcarroll** [comment]
done
