### ISSUE TITLE
💡 [FEAT] NIIMBOT printer compatibility 

### ISSUE THREAD

**Issue by dinobuccini** [MarksMakerSpace/filament-profiles#6]
**Is your feature request related to a problem? Please describe.**

NIIMBOT printers are unable to print from PDF (as far as I am aware) and the provided profile does not work with their software.

**Describe the solution you'd like**

- NIIMBOT software compatible profiles would be nice 
- The ability to save PDFs of the swatch profiles from the website (It would be nice if the spool icon was not in the QR code, if anything made optional)

**Describe alternatives you've considered**

Recreating the profiles - this would take considerable amount of time
Taking a screenshot of the page - the scaling is off
Saving a PDF from the Labelife profile - the scaling is off and is way too small for some reason when converted and moved to the NIIMBOT software.

**Additional context**

**Comment by markcarroll** [comment]
@dinobuccini are you able to send me a sample file from the Nimbot app? I can see how easy it would be to reverse engineer it.  

I can also work on the PDF scaling. 

Did you try printing the page? It should just show the label.

**Comment by dinobuccini** [comment]
My apologies, I am rereading my comment and noticing that I was typing PDF instead of PNG. 

Having a PNG with no borders posted directly on the site would be nice, I tried exporting from Labelife but it came out way too small and with a border I couldn't delete.

I will attach a blank 40x30mm sample file from the NIIMBOT software. Looks like they use .jcps file format.

[40x30mm Test.zip](https://github.com/user-attachments/files/16578285/40x30mm.Test.zip)

**Comment by markcarroll** [comment]
@dinobuccini can you send me a picture or screenshot of what that label looked like?

**Comment by markcarroll** [comment]
@dinobuccini Got good news for you.   I think I cracked the downloading as a PNG file.  Take a look and tell me what you think.

**Comment by dinobuccini** [comment]
Sorry for not getting to reply sooner - looks like you were able to figure out a solution. 

They came out great.

You are awesome - if you have an online tip jar of some kind please send it my way so I can make sure you get something for your time!

**Comment by markcarroll** [comment]
@dinobuccini glad it worked out for you, I was actually quite pleased with how it came out myself. It went better than I had initially thought.  

I do have a KoFi page: [https://ko-fi.com/sirthundercloud](https://ko-fi.com/sirthundercloud) should you feel so inclined.  Thank you.
