### ISSUE TITLE
🐛 [BUG] Product link not displaying.

### ISSUE THREAD

**Issue by mikebronner** [MarksMakerSpace/filament-profiles#63]
**Describe the bug**
Even though I have added a product link, it is not being displayed.

**To Reproduce**
1. Go to https://3dfilamentprofiles.com/filaments/2071/details

**Screenshots**
<img width="694" alt="Screenshot 2024-12-23 at 6 40 58 PM" src="https://github.com/user-attachments/assets/9c59b0ad-477a-4840-a11d-487e88705e09" />

<img width="1344" alt="Screenshot 2024-12-23 at 6 40 30 PM" src="https://github.com/user-attachments/assets/2779e9c7-8b1e-449a-b048-1c76e72e032d" />

**Comment by markcarroll** [comment]
Thank you for reporting this. `protopasta.com` accidentally hit my regular expression designed to clean and verify shortened URLs, in this case `a.co` was not specific enough.  This is now fixed.  Thank you again for letting me know.
