### ISSUE TITLE
💡 [FEAT] New material Type From 3DE

### ISSUE THREAD

**Issue by phiko-misc** [MarksMakerSpace/filament-profiles#67]
I have some filament from 3DE and it would be very nice to see PLA types `Max` and `X-Strong` as a Material type.
If they are added, it will also be much easier to find the material in my list.

**The solution**
It would be to add it.

**Alternatives solution**
It would be to not add it and then just say people need to use the types already available, like premium, or add two Brands, `3DE` and `3DE Max.` But I don't think this is a sustainable solution because the double branding would be confusing for some.

**Links to the material**
***X-Strong:*** https://3deksperten.dk/products/x-strong-pla-black-3de-premium-1-75mm
***Max:*** https://3deksperten.dk/collections/3de-premium-pla-max

**Comment by markcarroll** [comment]
done
