### ISSUE TITLE
Incorrectly created a new material instead of a new filament

### ISSUE THREAD

**Issue by codewise-nicolas** [MarksMakerSpace/filament-profiles#68]
I incorrectly created a new material https://3dfilamentprofiles.com/defaults/tronxy/pla/---other--- instead of a filament.
There is no way to remove or archive the material.
Can the editors please remove it. Thank you.

**Comment by markcarroll** [comment]
Ha, yeah, looks like I forgot a delete button.  No worries, I’ve removed it.
