### ISSUE TITLE
K value limited and printer/extruder/toolhead should be values to enter

### ISSUE THREAD

**Issue by mcfool12** [MarksMakerSpace/filament-profiles#7]
I am trying to add some of my filaments to the list and found that the K value only goes out to 3 digits for some reason.  Also the printer/extruder/toolhead should be fields also as values will be different per setup.

**Comment by mcfool12** [comment]
Also you are missing Qidi-Tech in the filament list.

**Comment by mcfool12** [comment]
Thanks will be getting some filaments added.  Also on the main page where you have the embedded hyperlink to go to the GitHub, you are missing a space between GitHub Repo and or.

**Comment by markcarroll** [comment]
Great catch. That is my kind of attention to detail.  Thanks for reporting.  I will fix today.   

One thing.  If you are adding a few colors of the same filament, add the defaults on the brands page first.  Then you can skip that on the filament forms and the defaults will get filled in for you.  Yes I know the UI on that needs improving.

**Comment by mcfool12** [comment]
Thanks for the heads up.

**Comment by davidfischer-ch** [comment]
I found that K-value depends not only of the hardware, but also of the print speed.

I compared against my own data (eSUN PLA+ mainly) and it look like the "scale" of the value entered in the database is matching the numbers I got from printing Pressure Advance Tower(s) with my high speed profile [1].

Meaning it was tested at ~ 300 mm/s -> Right ?

[1] On a Ender 5 Pro converted to a Mercury One.1

**Comment by markcarroll** [comment]
closing this as the original request has been implemented
