### ISSUE TITLE
💡 [FEAT] New Material Type: Polymaker PolySmooth

### ISSUE THREAD

**Issue by barlowtj48** [MarksMakerSpace/filament-profiles#70]
**Is your feature request related to a problem? Please describe.**
Yes, missing material

**Describe the solution you'd like**
Add PolySmooth material to Polymaker

**Describe alternatives you've considered**
Add it as another material, but this would be inaccurate

**Additional context**
[Link to material](https://us.polymaker.com/products/polysmooth?variant=39597627146297)

**Comment by markcarroll** [comment]
Looks like. PolySmooth is a PVB material, so I have added a material type of "PolySmooth". So https://3dfilamentprofiles.com/filaments/polymaker/pvb/polysmooth would be the place to put these.
