### ISSUE TITLE
🐛 [BUG] Add filament popup not able to be moved up/down

### ISSUE THREAD

**Issue by T9Air** [MarksMakerSpace/filament-profiles#8]
When I try to add a filament, the popup is too big for my screen to show at once, and I can not move the popup up/down in order to press the button to add the filament. I also can not access all the options.

**Desktop (please complete the following information):**
 Laptop with windows, using chrome

**Comment by markcarroll** [comment]
@T9Air eek! that's not good.  I will look into making it more responsive.

**Comment by T9Air** [comment]
1920 by 1080. It would probably be best to just add a scroll bar to the side of the popup, instead of changing the size of the popup.

**Comment by markcarroll** [comment]
ok that should be fixed. Thanks for reporting that.
